### PR TITLE
176916931 deploy to heroku

### PR DESCRIPTION
**Pull request by ToxicSam**
you guys can view the heroku app through [https://prairielearn-eecs.herokuapp.com/]. I'm adding you guys in

### CODE REVIEW

**Comment by klutzx92** [comment]
The link doesn't work for me. Can anyone else see it?

**Comment by timotiusvincent** [comment]
Link works now. Go ahead and merge

**Comment by fshamji** [comment]
the link works for me, but why do you define the development group twice?

**Comment by fshamji** [comment]
LGTM

**Pull request merged**
